name: tests

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        config:
          - ["Py3.9-Plone6", "3.9"]
          - ["Py3.10-Plone6", "3.10"]
          - ["Py3.11-Plone6", "3.11"]
    runs-on: ubuntu-latest
    name: ${{ matrix.config[0] }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.config[1] }}
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            **/eggs
            **/downloads
          key: ${{ runner.os }}-cache-${{ hashFiles('setup.*', '*.cfg') }}-${{ matrix.config[0] }}
          restore-keys: |
            ${{ runner.os }}-cache-
      - name: Install dependencies
        run: |
          python -m venv .
          bin/pip install -r requirements.txt
          bin/buildout -c .github.cfg
      - name: Pre commit
        uses: pre-commit/action@v2.0.0
        if: ${{ matrix.config[1] == '3.11' }}
      - name: Code Analysis
        run: |
          bin/code-analysis
        if: ${{ matrix.config[1] == '3.11' }}
      - name: Test
        run: |
          bin/coverage run bin/test -s recensio.plone
          bin/coverage report --fail-under=40 -i
        env:
          zope_i18n_compile_mo_files: 1
